(module
  (type $0 (func))
  (func $0 (type 0) (block (br 0)))
  (func $1 (type 0) (block (i32.const 1) (br_if 0)))
  (func $2 (type 0) (block (i32.const 0) (br_table 0)))
  (export "br" (func 0))
  (export "br_if" (func 1))
  (export "br_table" (func 2))
)
(assert_return (invoke "br"))
(assert_return (invoke "br_if"))
(assert_return (invoke "br_table"))
